source "https://rubygems.org"

gem "jekyll", :github => "jekyll/jekyll"
gem "solitude", :github => "ashmaroli/solitude"

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-admin'
  gem 'jekyll-sitemap'
end
